from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(QtWidgets.QMainWindow):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.setEnabled(True)
        AuthWindow.resize(370, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AuthWindow.sizePolicy().hasHeightForWidth())
        AuthWindow.setSizePolicy(sizePolicy)
        AuthWindow.setMinimumSize(QtCore.QSize(370, 380))
        AuthWindow.setMaximumSize(QtCore.QSize(370, 740))
        self.centralwidget = QtWidgets.QWidget(AuthWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AuthTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.AuthTabWidget.setGeometry(QtCore.QRect(10, 200, 351, 531))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AuthTabWidget.setFont(font)
        self.AuthTabWidget.setObjectName("AuthTabWidget")
        self.auth_tab = QtWidgets.QWidget()
        self.auth_tab.setObjectName("auth_tab")
        self.label_2 = QtWidgets.QLabel(self.auth_tab)
        self.label_2.setGeometry(QtCore.QRect(12, 9, 61, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.LoginTextEdit = QtWidgets.QPlainTextEdit(self.auth_tab)
        self.LoginTextEdit.setGeometry(QtCore.QRect(76, 13, 261, 31))
        self.LoginTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.LoginTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.LoginTextEdit.setObjectName("LoginTextEdit")
        self.label_3 = QtWidgets.QLabel(self.auth_tab)
        self.label_3.setGeometry(QtCore.QRect(11, 47, 61, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.PasswordTextEdit = QtWidgets.QPlainTextEdit(self.auth_tab)
        self.PasswordTextEdit.setGeometry(QtCore.QRect(76, 51, 261, 31))
        self.PasswordTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PasswordTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PasswordTextEdit.setObjectName("PasswordTextEdit")
        self.LoginButton = QtWidgets.QPushButton(self.auth_tab)
        self.LoginButton.setGeometry(QtCore.QRect(100, 90, 141, 31))
        self.LoginButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LoginButton.setObjectName("LoginButton")
        self.AuthTabWidget.addTab(self.auth_tab, "")
        self.regist_tab = QtWidgets.QWidget()
        self.regist_tab.setObjectName("regist_tab")
        self.RegistTextEdit = QtWidgets.QPlainTextEdit(self.regist_tab)
        self.RegistTextEdit.setGeometry(QtCore.QRect(10, 30, 321, 31))
        self.RegistTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistTextEdit.setObjectName("RegistTextEdit")
        self.label_6 = QtWidgets.QLabel(self.regist_tab)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 321, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.regist_tab)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 321, 21))
        self.label_7.setObjectName("label_7")
        self.RegistEmailTextEdit = QtWidgets.QPlainTextEdit(self.regist_tab)
        self.RegistEmailTextEdit.setGeometry(QtCore.QRect(10, 90, 321, 31))
        self.RegistEmailTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistEmailTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistEmailTextEdit.setObjectName("RegistEmailTextEdit")
        self.label_8 = QtWidgets.QLabel(self.regist_tab)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 321, 21))
        self.label_8.setObjectName("label_8")
        self.RegistPasswordTextEdit = QtWidgets.QPlainTextEdit(self.regist_tab)
        self.RegistPasswordTextEdit.setGeometry(QtCore.QRect(10, 150, 321, 31))
        self.RegistPasswordTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistPasswordTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistPasswordTextEdit.setObjectName("RegistPasswordTextEdit")
        self.label_9 = QtWidgets.QLabel(self.regist_tab)
        self.label_9.setGeometry(QtCore.QRect(10, 190, 321, 21))
        self.label_9.setObjectName("label_9")
        self.RegistPasswordDoubleTextEdit = QtWidgets.QPlainTextEdit(self.regist_tab)
        self.RegistPasswordDoubleTextEdit.setGeometry(QtCore.QRect(10, 210, 321, 31))
        self.RegistPasswordDoubleTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistPasswordDoubleTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RegistPasswordDoubleTextEdit.setObjectName("RegistPasswordDoubleTextEdit")
        self.label_10 = QtWidgets.QLabel(self.regist_tab)
        self.label_10.setGeometry(QtCore.QRect(10, 250, 321, 21))
        self.label_10.setObjectName("label_10")
        self.PhoneTextEdit = QtWidgets.QPlainTextEdit(self.regist_tab)
        self.PhoneTextEdit.setGeometry(QtCore.QRect(10, 270, 321, 31))
        self.PhoneTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PhoneTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PhoneTextEdit.setObjectName("PhoneTextEdit")
        self.label_11 = QtWidgets.QLabel(self.regist_tab)
        self.label_11.setGeometry(QtCore.QRect(10, 310, 321, 21))
        self.label_11.setObjectName("label_11")
        self.AboutTextEdit = QtWidgets.QPlainTextEdit(self.regist_tab)
        self.AboutTextEdit.setGeometry(QtCore.QRect(10, 330, 321, 131))
        self.AboutTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.AboutTextEdit.setObjectName("AboutTextEdit")
        self.line_3 = QtWidgets.QFrame(self.regist_tab)
        self.line_3.setGeometry(QtCore.QRect(10, 470, 321, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_12 = QtWidgets.QLabel(self.regist_tab)
        self.label_12.setGeometry(QtCore.QRect(10, 479, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.AuthTabWidget.addTab(self.regist_tab, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.IPTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.IPTextEdit.setGeometry(QtCore.QRect(20, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IPTextEdit.setFont(font)
        self.IPTextEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.IPTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.IPTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.IPTextEdit.setPlaceholderText("")
        self.IPTextEdit.setObjectName("IPTextEdit")
        self.PortTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.PortTextEdit.setGeometry(QtCore.QRect(280, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PortTextEdit.setFont(font)
        self.PortTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PortTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PortTextEdit.setObjectName("PortTextEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(186, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 29, 331, 41))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 160, 331, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.PingButton = QtWidgets.QPushButton(self.centralwidget)
        self.PingButton.setGeometry(QtCore.QRect(20, 120, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PingButton.setFont(font)
        self.PingButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.PingButton.setObjectName("PingButton")
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        self.AuthTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Вход"))
        self.label_2.setText(_translate("AuthWindow", "Логин:"))
        self.label_3.setText(_translate("AuthWindow", "Пароль:"))
        self.LoginButton.setText(_translate("AuthWindow", "Войти"))
        self.AuthTabWidget.setTabText(self.AuthTabWidget.indexOf(self.auth_tab), _translate("AuthWindow", "Вход"))
        self.label_6.setText(_translate("AuthWindow", "Введите ник в чате:"))
        self.label_7.setText(_translate("AuthWindow", "Введите Email/Логин:"))
        self.label_8.setText(_translate("AuthWindow", "Введите пароль:"))
        self.label_9.setText(_translate("AuthWindow", "Повторно введите пароль:"))
        self.label_10.setText(_translate("AuthWindow", "Телефон*:"))
        self.label_11.setText(_translate("AuthWindow", "О себе*:"))
        self.label_12.setText(_translate("AuthWindow", "* - необязательно заполнять"))
        self.AuthTabWidget.setTabText(self.AuthTabWidget.indexOf(self.regist_tab),
                                      _translate("AuthWindow", "Регистрация"))
        self.label.setText(_translate("AuthWindow",
                                      "<html><head/><body><p align=\"center\"><span style=\" color:#55557f;\">Corporative Chat</span><span style=\" color:#55557f; vertical-align:super;\">1.0 </span></p></body></html>"))
        self.label_4.setText(_translate("AuthWindow", "IP:"))
        self.IPTextEdit.setPlainText(_translate("AuthWindow", "255.255.255.255"))
        self.PortTextEdit.setPlainText(_translate("AuthWindow", "5000"))
        self.label_5.setText(_translate("AuthWindow", "Port:"))
        self.PingButton.setText(_translate("AuthWindow", "Проверить соединение с сервером"))

