# Form implementation generated from reading ui file 'C:\Users\Bananator\PycharmProjects\BorodaChat\client\gui_client\gui_design.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MessageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MessageLineEdit.setGeometry(QtCore.QRect(170, 330, 471, 31))
        self.MessageLineEdit.setObjectName("MessageLineEdit")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(650, 330, 81, 31))
        self.SendButton.setObjectName("SendButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(143, 20, 41, 341))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -1, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.UserLabel = QtWidgets.QLabel(self.centralwidget)
        self.UserLabel.setGeometry(QtCore.QRect(296, 0, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UserLabel.setFont(font)
        self.UserLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.UserLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.UserLabel.setObjectName("UserLabel")
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(10, 370, 141, 23))
        self.UpdateButton.setObjectName("UpdateButton")
        self.UserList = QtWidgets.QListWidget(self.centralwidget)
        self.UserList.setGeometry(QtCore.QRect(5, 31, 151, 331))
        self.UserList.setObjectName("UserList")
        self.MessageList = QtWidgets.QListWidget(self.centralwidget)
        self.MessageList.setGeometry(QtCore.QRect(175, 30, 561, 291))
        self.MessageList.setObjectName("MessageList")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Corporative Chat 1.0"))
        self.SendButton.setText(_translate("MainWindow", "Отправить"))
        self.label.setText(_translate("MainWindow", "Пользователи:"))
        self.label_2.setText(_translate("MainWindow", "Сообщения:"))
        self.UserLabel.setText(_translate("MainWindow", "Пользователь"))
        self.UpdateButton.setText(_translate("MainWindow", "Обновить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
